qube_version: '2.6.1 # <<QUBE_NO_BUMP>>'
full_name: Sven Fillinger
email: sven.fillinger@qbic.uni-tuebingen.de
project_name: ukt-diagnostics
project_short_description: ukt-diagnostics. A qube based .
version: 1.3.0
domain: portlet
language: groovy
project_slug: ukt-diagnostics
project_slug_no_hyphen: ukt_diagnostics
template_version: '1.0.4 # <<QUBE_NO_BUMP>>'
template_handle: portlet-groovy
github_username: sven1103
creator_github_username: sven1103
is_github_repo: false
is_repo_private: false
is_github_orga: false
copyright_holder: QBiC
license: MIT
main_class_prefix: Qbic
use_openbis_client: yes
use_openbis_raw_api: yes
use_qbic_databases: no
use_vaadin_charts: no
